apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "workfx-ai.fullname" . }}-config
  labels:
    {{- include "workfx-ai.labels" . | nindent 4 }}
data:
  # Basic application configuration
  ENV: {{ .Values.config.environment | quote }}
  CLOUD_TYPE: {{ .Values.config.cloudProvider | quote }}
  KA_NAME: {{ .Values.config.kaName | quote }}
  
  # OpenTelemetry configuration
  ENABLE_OPTEL: {{ .Values.config.enableOtel | quote }}
  OTEL_SERVICE_NAME: {{ .Values.config.otelServiceName | quote }}
  
  {{- if .Values.config.applicationInsightsConnectionString }}
  APPLICATIONINSIGHTS_CONNECTION_STRING: {{ .Values.config.applicationInsightsConnectionString | quote }}
  {{- end }}
  
  # Azure-specific configuration
  {{- if eq .Values.config.cloudProvider "azure" }}
  TENANT_ID: {{ .Values.azure.tenantId | quote }}
  AZURE_KEYVAULT_URL: {{ .Values.azure.keyVaultUrl | quote }}
  AKS_MANAGED_IDENTITY: {{ .Values.azure.aksManagedIdentity | quote }}
  
  # Storage configuration
  STORAGE_TYPE: {{ .Values.azure.storage.type | quote }}
  STORAGE_BUCKET_URI_PATH: {{ .Values.azure.storage.bucketUriPath | quote }}
  STORAGE_ADMIN_BUCKET_NAME: {{ .Values.azure.storage.adminBucketName | quote }}
  STORAGE_USER_BUCKET_NAME: {{ .Values.azure.storage.userBucketName | quote }}
  STORAGE_PUBLIC_BUCKET_NAME: {{ .Values.azure.storage.publicBucketName | quote }}
  STORAGE_TOOLS_IMAGE_BUCKET_NAME: {{ .Values.azure.storage.toolsImageBucketName | quote }}
  {{- end }}
  
  # Model configuration
  EMBEDDING_MODEL_PROVIDER: {{ .Values.models.embedding.provider | quote }}
  EMBEDDING_MODEL_NAME: {{ .Values.models.embedding.name | quote }}
  RERANK_MODEL_PROVIDER: {{ .Values.models.rerank.provider | quote }}
  RERANK_MODEL_NAME: {{ .Values.models.rerank.name | quote }}
  
  # Service endpoints (internal)
  {{- $fullname := include "workfx-ai.fullname" . }}
  {{- $namespace := .Release.Namespace }}
  MANAGEMENT_INTERNAL_SERVICE_ENDPOINT: "http://{{ $fullname }}:{{ .Values.service.port }}"
  AI_INTERNAL_SERVICE_ENDPOINT: "http://{{ $fullname }}:{{ .Values.service.port }}"
  MANAGEMENT_INTERNAL_SERVICE_ENDPOINT_WITH_NAMESPACE: "http://{{ $fullname }}.{{ $namespace }}.svc.cluster.local:{{ .Values.service.port }}"
  
  # Elasticsearch configuration
  {{- if .Values.elasticsearch.enabled }}
  ELASTICSEARCH_URL: {{ .Values.elasticsearch.url | quote }}
  {{- end }}
  
  # Kafka configuration  
  {{- if .Values.kafka.enabled }}
  KAFKA_BROKERS: {{ .Values.kafka.brokers | quote }}
  {{- end }}
