{{- if .Values.configmap.create }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "workfx-ai.fullname" . }}-config
  labels:
    {{- include "workfx-ai.labels" . | nindent 4 }}
data:
  # Global Configuration
  ENV: {{ .Values.global.environment | quote }}
  APP_NAME: {{ .Values.global.appName | quote }}
  LOG_LEVEL: {{ .Values.global.logLevel | quote }}
  CLOUD_TYPE: {{ .Values.global.cloudProvider | quote }}
  
  # Cloud Provider Configuration
  {{- if eq .Values.global.cloudProvider "azure" }}
  AZURE_KEYVAULT_URL: {{ .Values.global.azure.keyVaultUrl | quote }}
  AZURE_CLIENT_ID: {{ .Values.global.azure.clientId | quote }}
  AZURE_CLIENT_SECRET: {{ .Values.global.azure.clientSecret | quote }}
  AZURE_TENANT_ID: {{ .Values.global.azure.tenantId | quote }}
  {{- end }}
  
  {{- if eq .Values.global.cloudProvider "aws" }}
  AWS_REGION: {{ .Values.global.aws.region | quote }}
  AWS_ACCESS_KEY_ID: {{ .Values.global.aws.accessKeyId | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.global.aws.secretAccessKey | quote }}
  {{- end }}
  
  {{- if eq .Values.global.cloudProvider "gcp" }}
  GCP_PROJECT_ID: {{ .Values.global.gcp.projectId | quote }}
  GCP_REGION: {{ .Values.global.gcp.region | quote }}
  {{- end }}
  
  # Application Configuration
  KA_NAME: {{ .Values.config.kaName | quote }}
  ENABLE_OPTEL: {{ .Values.config.enableOtel | quote }}
  
  # Storage Configuration
  STORAGE_TYPE: {{ .Values.workfx.storage.type | quote }}
  STORAGE_BUCKET_URI_PATH: {{ .Values.workfx.storage.bucketUriPath | quote }}
  STORAGE_ADMIN_BUCKET_NAME: {{ .Values.workfx.storage.adminBucketName | quote }}
  STORAGE_USER_BUCKET_NAME: {{ .Values.workfx.storage.userBucketName | quote }}
  STORAGE_PUBLIC_BUCKET_NAME: {{ .Values.workfx.storage.publicBucketName | quote }}
  STORAGE_EMAIL_BUCKET_NAME: {{ .Values.workfx.storage.emailBucketName | quote }}
  STORAGE_TOOLS_IMAGE_BUCKET_NAME: {{ .Values.workfx.storage.toolsImageBucketName | quote }}
  STORAGE_UPLOAD_FILE_SIZE_LIMIT: {{ .Values.workfx.storage.uploadFileSizeLimit | quote }}
  STORAGE_UPLOAD_IMAGE_FILE_SIZE_LIMIT: {{ .Values.workfx.storage.uploadImageFileSizeLimit | quote }}
  STORAGE_UPLOAD_VIDEO_FILE_SIZE_LIMIT: {{ .Values.workfx.storage.uploadVideoFileSizeLimit | quote }}
  STORAGE_UPLOAD_AUDIO_FILE_SIZE_LIMIT: {{ .Values.workfx.storage.uploadAudioFileSizeLimit | quote }}
  STORAGE_FILES_ACCESS_TIMEOUT: {{ .Values.workfx.storage.filesAccessTimeout | quote }}
  
  # Billing Configuration
  ENABLE_BILLING: {{ .Values.workfx.billing.enabled | quote }}
  ENABLE_STRIPE: {{ .Values.workfx.billing.stripe.enabled | quote }}
  
  # Integrations Configuration
  JINA_API_KEY: {{ .Values.workfx.integrations.jinaApiKey | quote }}
  
  # Model Configuration
  EMBEDDING_MODEL_PROVIDER: {{ .Values.config.models.embedding.provider | quote }}
  EMBEDDING_MODEL: {{ .Values.config.models.embedding.name | quote }}
  RERANK_MODEL_PROVIDER: {{ .Values.config.models.rerank.provider | quote }}
  RERANK_MODEL: {{ .Values.config.models.rerank.name | quote }}
  
  # RAG Configuration
  RAG_SUMMARY_BOOST: {{ .Values.config.rag.summaryBoost | quote }}
  RAG_CONTENT_BOOST: {{ .Values.config.rag.contentBoost | quote }}
  RAG_DISTILLED_KNOWLEDGE_BOOST: {{ .Values.config.rag.distilledKnowledgeBoost | quote }}
  RAG_KEYWORDS_BOOST: {{ .Values.config.rag.keywordsBoost | quote }}
  RAG_DEFAULT_SEARCH_LIMIT: {{ .Values.config.rag.defaultSearchLimit | quote }}
  RAG_MAX_SEARCH_LIMIT: {{ .Values.config.rag.maxSearchLimit | quote }}
  RAG_DEFAULT_VECTOR_K: {{ .Values.config.rag.defaultVectorK | quote }}
  RAG_DEFAULT_NUM_CANDIDATES: {{ .Values.config.rag.defaultNumCandidates | quote }}
  RAG_VECTOR_SIMILARITY_THRESHOLD: {{ .Values.config.rag.vectorSimilarityThreshold | quote }}
  RAG_RERANK_TOP_K: {{ .Values.config.rag.rerankTopK | quote }}
  RAG_RERANK_SCORE_THRESHOLD: {{ .Values.config.rag.rerankScoreThreshold | quote }}
  RAG_SEARCH_TIMEOUT: {{ .Values.config.rag.searchTimeout | quote }}
  RAG_EMBEDDING_TIMEOUT: {{ .Values.config.rag.embeddingTimeout | quote }}
  RAG_ENABLE_CACHING: {{ .Values.config.rag.enableCaching | quote }}
  RAG_CACHE_TTL_SECONDS: {{ .Values.config.rag.cacheTtlSeconds | quote }}
  
  # Rate Limiting Configuration
  RATE_LIMIT_ENABLED: {{ .Values.config.rateLimit.enabled | quote }}
  RATE_LIMIT_REDIS_KEY_PREFIX: {{ .Values.config.rateLimit.redisKeyPrefix | quote }}
  RATE_LIMIT_REDIS_KEY_EXPIRE_BUFFER: {{ .Values.config.rateLimit.redisKeyExpireBuffer | quote }}
  RATE_LIMIT_IP_ENABLED: {{ .Values.config.rateLimit.ipEnabled | quote }}
  RATE_LIMIT_TENANT_ENABLED: {{ .Values.config.rateLimit.tenantEnabled | quote }}
  RATE_LIMIT_AGENT_MESSAGE_ENABLED: {{ .Values.config.rateLimit.agentMessageEnabled | quote }}
  RATE_LIMIT_MINUTE_WINDOW: {{ .Values.config.rateLimit.minuteWindow | quote }}
  RATE_LIMIT_HOUR_WINDOW: {{ .Values.config.rateLimit.hourWindow | quote }}
  RATE_LIMIT_DAY_WINDOW: {{ .Values.config.rateLimit.dayWindow | quote }}
  RATE_LIMIT_WEEKLY_WINDOW: {{ .Values.config.rateLimit.weeklyWindow | quote }}
  RATE_LIMIT_MONTHLY_WINDOW: {{ .Values.config.rateLimit.monthlyWindow | quote }}
  RATE_LIMIT_MINUTE_LIMIT_RATIO: {{ .Values.config.rateLimit.minuteLimitRatio | quote }}
  RATE_LIMIT_DAILY_LIMIT_HOURS: {{ .Values.config.rateLimit.dailyLimitHours | quote }}
  RATE_LIMIT_IP_TENANT_RATIO: {{ .Values.config.rateLimit.ipTenantRatio | quote }}
  RATE_LIMIT_GLOBAL_REQUESTS_PER_HOUR: {{ .Values.config.rateLimit.globalRequestsPerHour | quote }}
  RATE_LIMIT_GLOBAL_REQUESTS_PER_MINUTE: {{ .Values.config.rateLimit.globalRequestsPerMinute | quote }}
  RATE_LIMIT_GLOBAL_REQUESTS_PER_DAY: {{ .Values.config.rateLimit.globalRequestsPerDay | quote }}
  RATE_LIMIT_TENANT_CAPACITY_MULTIPLIER: {{ .Values.config.rateLimit.tenantCapacityMultiplier | quote }}
  RATE_LIMIT_DEFAULT_TENANT_REQUESTS_PER_HOUR: {{ .Values.config.rateLimit.defaultTenantRequestsPerHour | quote }}
  RATE_LIMIT_DEFAULT_TENANT_REQUESTS_PER_MINUTE: {{ .Values.config.rateLimit.defaultTenantRequestsPerMinute | quote }}
  RATE_LIMIT_DEFAULT_TENANT_REQUESTS_PER_DAY: {{ .Values.config.rateLimit.defaultTenantRequestsPerDay | quote }}
  RATE_LIMIT_IP_REQUESTS_PER_HOUR: {{ .Values.config.rateLimit.ipRequestsPerHour | quote }}
  RATE_LIMIT_IP_REQUESTS_PER_MINUTE: {{ .Values.config.rateLimit.ipRequestsPerMinute | quote }}
  RATE_LIMIT_IP_REQUESTS_PER_DAY: {{ .Values.config.rateLimit.ipRequestsPerDay | quote }}
  RATE_LIMIT_AGENT_INVOKE_REQUESTS_PER_HOUR: {{ .Values.config.rateLimit.agentInvokeRequestsPerHour | quote }}
  RATE_LIMIT_AGENT_INVOKE_REQUESTS_PER_MINUTE: {{ .Values.config.rateLimit.agentInvokeRequestsPerMinute | quote }}
  RATE_LIMIT_AGENT_INVOKE_REQUESTS_PER_DAY: {{ .Values.config.rateLimit.agentInvokeRequestsPerDay | quote }}
  RATE_LIMIT_EXTERNAL_API_REQUESTS_PER_HOUR: {{ .Values.config.rateLimit.externalApiRequestsPerHour | quote }}
  RATE_LIMIT_EXTERNAL_API_REQUESTS_PER_MINUTE: {{ .Values.config.rateLimit.externalApiRequestsPerMinute | quote }}
  RATE_LIMIT_EXTERNAL_API_REQUESTS_PER_DAY: {{ .Values.config.rateLimit.externalApiRequestsPerDay | quote }}
  RATE_LIMIT_KA_TENANT_MULTIPLIER: {{ .Values.config.rateLimit.kaTenantMultiplier | quote }}
  RATE_LIMIT_KA_TENANT_BYPASS: {{ .Values.config.rateLimit.kaTenantBypassRateLimit | quote }}
  
  # URL Extractor Configuration
  URL_EXTRACTOR_SITEMAP_MAX_SIZE: {{ .Values.config.urlExtractor.sitemapMaxSize | quote }}
  URL_EXTRACTOR_SITEMAP_TIMEOUT: {{ .Values.config.urlExtractor.sitemapTimeout | quote }}
  URL_EXTRACTOR_MAX_SITEMAP_INDEX_SIZE: {{ .Values.config.urlExtractor.maxSitemapIndexSize | quote }}
  URL_EXTRACTOR_JINA_BASE_URL: {{ .Values.config.urlExtractor.jinaBaseUrl | quote }}
  URL_EXTRACTOR_JINA_TIMEOUT: {{ .Values.config.urlExtractor.jinaTimeout | quote }}
  URL_EXTRACTOR_ENABLE_SITEMAP: {{ .Values.config.urlExtractor.enableSitemap | quote }}
  URL_EXTRACTOR_ENABLE_PROVIDER: {{ .Values.config.urlExtractor.enableProvider | quote }}
  URL_EXTRACTOR_ENABLE_DUPLICATE_REMOVAL: {{ .Values.config.urlExtractor.enableDuplicateRemoval | quote }}
  
  # Service Endpoints
  MANAGEMENT_INTERNAL_SERVICE_ENDPOINT: {{ .Values.workfx.api.service.endpoint | quote }}
  
  # Custom Configuration
  {{- range $key, $value := .Values.workfx.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
