{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "workfx-ai.secretName" . }}
  labels:
    {{- include "workfx-ai.labels" . | nindent 4 }}
type: Opaque
data:
  # Database configuration
  {{- if .Values.database.external }}
  database-url: {{ include "workfx-ai.databaseUrl" . | b64enc }}
  {{- else }}
  database-password: {{ .Values.secrets.values.dbPassword | b64enc }}
  {{- end }}
  
  # Redis configuration
  {{- if .Values.redis.external }}
  redis-url: {{ include "workfx-ai.redisUrl" . | b64enc }}
  {{- else }}
  redis-password: {{ .Values.secrets.values.redisPassword | b64enc }}
  {{- end }}
  
  # Application secrets
  {{- if .Values.secrets.values.secretKey }}
  SECRET_KEY: {{ .Values.secrets.values.secretKey | b64enc }}
  {{- end }}
  
  {{- if .Values.secrets.values.openaiApiKey }}
  OPENAI_API_KEY: {{ .Values.secrets.values.openaiApiKey | b64enc }}
  {{- end }}
  
  {{- if .Values.secrets.values.googleClientSecret }}
  GOOGLE_CLIENT_SECRET: {{ .Values.secrets.values.googleClientSecret | b64enc }}
  {{- end }}
  
  # Azure client secret
  {{- if .Values.secrets.values.azureClientSecret }}
  AZURE_CLIENT_SECRET: {{ .Values.secrets.values.azureClientSecret | b64enc }}
  {{- end }}
{{- end }}
