{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "workfx-ai.secretName" . }}
  labels:
    {{- include "workfx-ai.labels" . | nindent 4 }}
type: Opaque
data:
  # Database Configuration (pg-secret)
  {{- if .Values.secrets.database }}
  # Direct field names
  host: {{ .Values.secrets.database.host | b64enc }}
  port: {{ .Values.secrets.database.port | toString | b64enc }}
  username: {{ .Values.secrets.database.username | b64enc }}
  password: {{ .Values.secrets.database.password | b64enc }}
  database: {{ .Values.secrets.database.database | b64enc }}
  
  # Secret ID prefixed field names
  pg-secret_host: {{ .Values.secrets.database.host | b64enc }}
  pg-secret_port: {{ .Values.secrets.database.port | toString | b64enc }}
  pg-secret_username: {{ .Values.secrets.database.username | b64enc }}
  pg-secret_password: {{ .Values.secrets.database.password | b64enc }}
  pg-secret_database: {{ .Values.secrets.database.database | b64enc }}
  
  # Class name prefixed field names
  DatabaseSettings_host: {{ .Values.secrets.database.host | b64enc }}
  DatabaseSettings_port: {{ .Values.secrets.database.port | toString | b64enc }}
  DatabaseSettings_username: {{ .Values.secrets.database.username | b64enc }}
  DatabaseSettings_password: {{ .Values.secrets.database.password | b64enc }}
  DatabaseSettings_database: {{ .Values.secrets.database.database | b64enc }}
  {{- end }}
  
  # Redis Configuration (tp-redis-secret)
  {{- if .Values.secrets.redis }}
  # Direct field names
  redis_host: {{ .Values.secrets.redis.redis_host | b64enc }}
  redis_port: {{ .Values.secrets.redis.redis_port | toString | b64enc }}
  redis_password: {{ .Values.secrets.redis.redis_password | b64enc }}
  redis_db: {{ .Values.secrets.redis.redis_db | toString | b64enc }}
  redis_use_ssl: {{ .Values.secrets.redis.redis_use_ssl | toString | b64enc }}
  
  # Secret ID prefixed field names
  tp-redis-secret_redis_host: {{ .Values.secrets.redis.redis_host | b64enc }}
  tp-redis-secret_redis_port: {{ .Values.secrets.redis.redis_port | toString | b64enc }}
  tp-redis-secret_redis_password: {{ .Values.secrets.redis.redis_password | b64enc }}
  tp-redis-secret_redis_db: {{ .Values.secrets.redis.redis_db | toString | b64enc }}
  tp-redis-secret_redis_use_ssl: {{ .Values.secrets.redis.redis_use_ssl | toString | b64enc }}
  
  # Class name prefixed field names
  RedisSettings_redis_host: {{ .Values.secrets.redis.redis_host | b64enc }}
  RedisSettings_redis_port: {{ .Values.secrets.redis.redis_port | toString | b64enc }}
  RedisSettings_redis_password: {{ .Values.secrets.redis.redis_password | b64enc }}
  RedisSettings_redis_db: {{ .Values.secrets.redis.redis_db | toString | b64enc }}
  RedisSettings_redis_use_ssl: {{ .Values.secrets.redis.redis_use_ssl | toString | b64enc }}
  {{- end }}
  
  # Elasticsearch Configuration (es-secret)
  {{- if .Values.secrets.elasticsearch }}
  # Direct field names
  host: {{ .Values.secrets.elasticsearch.host | b64enc }}
  port: {{ .Values.secrets.elasticsearch.port | toString | b64enc }}
  username: {{ .Values.secrets.elasticsearch.username | b64enc }}
  password: {{ .Values.secrets.elasticsearch.password | b64enc }}
  use_ssl: {{ .Values.secrets.elasticsearch.use_ssl | toString | b64enc }}
  cluster_url: {{ .Values.secrets.elasticsearch.cluster_url | b64enc }}
  
  # Secret ID prefixed field names
  es-secret_host: {{ .Values.secrets.elasticsearch.host | b64enc }}
  es-secret_port: {{ .Values.secrets.elasticsearch.port | toString | b64enc }}
  es-secret_username: {{ .Values.secrets.elasticsearch.username | b64enc }}
  es-secret_password: {{ .Values.secrets.elasticsearch.password | b64enc }}
  es-secret_use_ssl: {{ .Values.secrets.elasticsearch.use_ssl | toString | b64enc }}
  es-secret_cluster_url: {{ .Values.secrets.elasticsearch.cluster_url | b64enc }}
  
  # Class name prefixed field names
  ElasticsearchSettings_host: {{ .Values.secrets.elasticsearch.host | b64enc }}
  ElasticsearchSettings_port: {{ .Values.secrets.elasticsearch.port | toString | b64enc }}
  ElasticsearchSettings_username: {{ .Values.secrets.elasticsearch.username | b64enc }}
  ElasticsearchSettings_password: {{ .Values.secrets.elasticsearch.password | b64enc }}
  ElasticsearchSettings_use_ssl: {{ .Values.secrets.elasticsearch.use_ssl | toString | b64enc }}
  ElasticsearchSettings_cluster_url: {{ .Values.secrets.elasticsearch.cluster_url | b64enc }}
  {{- end }}
  
  # JWT Configuration (jwt-secret)
  {{- if .Values.secrets.jwt }}
  # Direct field names
  admin_jwt_key: {{ .Values.secrets.jwt.admin_jwt_key | b64enc }}
  admin_jwt_issuer: {{ .Values.secrets.jwt.admin_jwt_issuer | b64enc }}
  admin_jwt_audience: {{ .Values.secrets.jwt.admin_jwt_audience | b64enc }}
  ai_jwt_key: {{ .Values.secrets.jwt.ai_jwt_key | b64enc }}
  ai_jwt_issuer: {{ .Values.secrets.jwt.ai_jwt_issuer | b64enc }}
  ai_jwt_audience: {{ .Values.secrets.jwt.ai_jwt_audience | b64enc }}
  
  # Secret ID prefixed field names
  jwt-secret_admin_jwt_key: {{ .Values.secrets.jwt.admin_jwt_key | b64enc }}
  jwt-secret_admin_jwt_issuer: {{ .Values.secrets.jwt.admin_jwt_issuer | b64enc }}
  jwt-secret_admin_jwt_audience: {{ .Values.secrets.jwt.admin_jwt_audience | b64enc }}
  jwt-secret_ai_jwt_key: {{ .Values.secrets.jwt.ai_jwt_key | b64enc }}
  jwt-secret_ai_jwt_issuer: {{ .Values.secrets.jwt.ai_jwt_issuer | b64enc }}
  jwt-secret_ai_jwt_audience: {{ .Values.secrets.jwt.ai_jwt_audience | b64enc }}
  
  # Class name prefixed field names
  JwtSettings_admin_jwt_key: {{ .Values.secrets.jwt.admin_jwt_key | b64enc }}
  JwtSettings_admin_jwt_issuer: {{ .Values.secrets.jwt.admin_jwt_issuer | b64enc }}
  JwtSettings_admin_jwt_audience: {{ .Values.secrets.jwt.admin_jwt_audience | b64enc }}
  JwtSettings_ai_jwt_key: {{ .Values.secrets.jwt.ai_jwt_key | b64enc }}
  JwtSettings_ai_jwt_issuer: {{ .Values.secrets.jwt.ai_jwt_issuer | b64enc }}
  JwtSettings_ai_jwt_audience: {{ .Values.secrets.jwt.ai_jwt_audience | b64enc }}
  {{- end }}
  
  # Security Configuration (secret-key)
  {{- if .Values.secrets.security }}
  # Direct field names
  data_secret: {{ .Values.secrets.security.data_secret | b64enc }}
  jina_api_key: {{ .Values.secrets.security.jina_api_key | b64enc }}
  
  # Secret ID prefixed field names
  secret-key_data_secret: {{ .Values.secrets.security.data_secret | b64enc }}
  secret-key_jina_api_key: {{ .Values.secrets.security.jina_api_key | b64enc }}
  
  # Class name prefixed field names
  SecuritySettings_data_secret: {{ .Values.secrets.security.data_secret | b64enc }}
  SecuritySettings_jina_api_key: {{ .Values.secrets.security.jina_api_key | b64enc }}
  {{- end }}
  
  # Kafka Configuration (wfx-kafka-secret)
  {{- if .Values.secrets.kafka }}
  # Direct field names
  bootstrap_servers: {{ .Values.secrets.kafka.bootstrap_servers | b64enc }}
  security_protocol: {{ .Values.secrets.kafka.security_protocol | b64enc }}
  document_chunks_topic: {{ .Values.secrets.kafka.document_chunks_topic | b64enc }}
  agents_topic: {{ .Values.secrets.kafka.agents_topic | b64enc }}
  consumer_group_prefix: {{ .Values.secrets.kafka.consumer_group_prefix | b64enc }}
  username: {{ .Values.secrets.kafka.username | b64enc }}
  password: {{ .Values.secrets.kafka.password | b64enc }}
  
  # Secret ID prefixed field names
  wfx-kafka-secret_bootstrap_servers: {{ .Values.secrets.kafka.bootstrap_servers | b64enc }}
  wfx-kafka-secret_security_protocol: {{ .Values.secrets.kafka.security_protocol | b64enc }}
  wfx-kafka-secret_document_chunks_topic: {{ .Values.secrets.kafka.document_chunks_topic | b64enc }}
  wfx-kafka-secret_agents_topic: {{ .Values.secrets.kafka.agents_topic | b64enc }}
  wfx-kafka-secret_consumer_group_prefix: {{ .Values.secrets.kafka.consumer_group_prefix | b64enc }}
  wfx-kafka-secret_username: {{ .Values.secrets.kafka.username | b64enc }}
  wfx-kafka-secret_password: {{ .Values.secrets.kafka.password | b64enc }}
  
  # Class name prefixed field names
  KafkaSettings_bootstrap_servers: {{ .Values.secrets.kafka.bootstrap_servers | b64enc }}
  KafkaSettings_security_protocol: {{ .Values.secrets.kafka.security_protocol | b64enc }}
  KafkaSettings_document_chunks_topic: {{ .Values.secrets.kafka.document_chunks_topic | b64enc }}
  KafkaSettings_agents_topic: {{ .Values.secrets.kafka.agents_topic | b64enc }}
  KafkaSettings_consumer_group_prefix: {{ .Values.secrets.kafka.consumer_group_prefix | b64enc }}
  KafkaSettings_username: {{ .Values.secrets.kafka.username | b64enc }}
  KafkaSettings_password: {{ .Values.secrets.kafka.password | b64enc }}
  {{- end }}
  
  # Payment Gateway Configuration (wfx-payment-gateway-secret)
  {{- if .Values.secrets.payment_gateway }}
  # Direct field names
  stripe_api_key: {{ .Values.secrets.payment_gateway.stripe.api_key | b64enc }}
  stripe_webhook_secret: {{ .Values.secrets.payment_gateway.stripe.webhook_secret | b64enc }}
  stripe_publishable_key: {{ .Values.secrets.payment_gateway.stripe.publishable_key | b64enc }}
  
  # Secret ID prefixed field names
  wfx-payment-gateway-secret_stripe_api_key: {{ .Values.secrets.payment_gateway.stripe.api_key | b64enc }}
  wfx-payment-gateway-secret_stripe_webhook_secret: {{ .Values.secrets.payment_gateway.stripe.webhook_secret | b64enc }}
  wfx-payment-gateway-secret_stripe_publishable_key: {{ .Values.secrets.payment_gateway.stripe.publishable_key | b64enc }}
  
  # Class name prefixed field names
  PaymentGatewaySettings_stripe_api_key: {{ .Values.secrets.payment_gateway.stripe.api_key | b64enc }}
  PaymentGatewaySettings_stripe_webhook_secret: {{ .Values.secrets.payment_gateway.stripe.webhook_secret | b64enc }}
  PaymentGatewaySettings_stripe_publishable_key: {{ .Values.secrets.payment_gateway.stripe.publishable_key | b64enc }}
  {{- end }}
  
  # Agent Evaluation Configuration (wfx-agent-evaluation-secret)
  {{- if .Values.secrets.agent_evaluation }}
  # Direct field names
  endpoint: {{ .Values.secrets.agent_evaluation.endpoint | b64enc }}
  api_key: {{ .Values.secrets.agent_evaluation.api_key | b64enc }}
  
  # Secret ID prefixed field names
  wfx-agent-evaluation-secret_endpoint: {{ .Values.secrets.agent_evaluation.endpoint | b64enc }}
  wfx-agent-evaluation-secret_api_key: {{ .Values.secrets.agent_evaluation.api_key | b64enc }}
  
  # Class name prefixed field names
  AgentEvaluationSettings_endpoint: {{ .Values.secrets.agent_evaluation.endpoint | b64enc }}
  AgentEvaluationSettings_api_key: {{ .Values.secrets.agent_evaluation.api_key | b64enc }}
  {{- end }}
  
  # Azure Storage Connection (azure-storage-connection-string)
  {{- if .Values.secrets.azure_storage }}
  # Direct field names
  azure_connection_string: {{ .Values.secrets.azure_storage.azure_connection_string | b64enc }}
  
  # Secret ID prefixed field names
  azure-storage-connection-string_azure_connection_string: {{ .Values.secrets.azure_storage.azure_connection_string | b64enc }}
  
  # Class name prefixed field names
  AzureStorageConnectionSettings_azure_connection_string: {{ .Values.secrets.azure_storage.azure_connection_string | b64enc }}
  {{- end }}
  
  # Internal API Keys (internal-service-key)
  {{- if .Values.secrets.internal_api_keys }}
  # Direct field names
  internal_api_keys: {{ .Values.secrets.internal_api_keys.internal_api_keys | toJson | b64enc }}
  
  # Secret ID prefixed field names
  internal-service-key_internal_api_keys: {{ .Values.secrets.internal_api_keys.internal_api_keys | toJson | b64enc }}
  
  # Class name prefixed field names
  InternalApiKeySettings_internal_api_keys: {{ .Values.secrets.internal_api_keys.internal_api_keys | toJson | b64enc }}
  {{- end }}
  
  # Global environment variables
  CLOUD_TYPE: {{ .Values.global.cloudProvider | b64enc }}
  ENV: {{ .Values.global.environment | b64enc }}
  APP_NAME: {{ .Values.global.appName | b64enc }}
  LOG_LEVEL: {{ .Values.global.logLevel | b64enc }}
  
  # Cloud provider specific environment variables
  {{- if eq .Values.global.cloudProvider "azure" }}
  AZURE_KEYVAULT_URL: {{ .Values.global.azure.keyVaultUrl | b64enc }}
  AZURE_CLIENT_ID: {{ .Values.global.azure.clientId | b64enc }}
  AZURE_CLIENT_SECRET: {{ .Values.global.azure.clientSecret | b64enc }}
  AZURE_TENANT_ID: {{ .Values.global.azure.tenantId | b64enc }}
  {{- end }}
  
  {{- if eq .Values.global.cloudProvider "aws" }}
  AWS_REGION: {{ .Values.global.aws.region | b64enc }}
  AWS_ACCESS_KEY_ID: {{ .Values.global.aws.accessKeyId | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.global.aws.secretAccessKey | b64enc }}
  {{- end }}
  
  {{- if eq .Values.global.cloudProvider "gcp" }}
  GCP_PROJECT_ID: {{ .Values.global.gcp.projectId | b64enc }}
  {{- end }}
{{- end }}
