# Azure Production Environment Example
# This file shows how to configure WorkFX-AI for Azure production

# Override base values for Azure production
global:
  environment: "prod"
  cloudProvider: "azure"
  imageRegistry: "yourregistry.azurecr.io"
  storageClass: "managed-premium"
  domain: "workfx.ai"

# Azure-specific image configuration
image:
  api:
    repository: "yourregistry.azurecr.io/workfx-ai-api"
    tag: "v1.0.0"
  cdc:
    repository: "yourregistry.azurecr.io/workfx-ai-cdc"
    tag: "v1.0.0"
  idb:
    repository: "yourregistry.azurecr.io/workfx-ai-idb"
    tag: "v1.0.0"

# Production resource allocation
workfx:
  api:
    replicas: 3
    resources:
      limits:
        cpu: "2000m"
        memory: "2Gi"
      requests:
        cpu: "1000m"
        memory: "1Gi"
    autoscaling:
      enabled: true
      minReplicas: 3
      maxReplicas: 10
      targetCPUUtilizationPercentage: 70
      targetMemoryUtilizationPercentage: 80
  
  cdc:
    replicas: 3
    resources:
      limits:
        cpu: "1000m"
        memory: "1Gi"
      requests:
        cpu: "500m"
        memory: "512Mi"
    autoscaling:
      enabled: true
      minReplicas: 3
      maxReplicas: 8
      targetCPUUtilizationPercentage: 70
  
  idb:
    replicas: 3
    resources:
      limits:
        cpu: "1000m"
        memory: "1Gi"
      requests:
        cpu: "500m"
        memory: "512Mi"
    autoscaling:
      enabled: true
      minReplicas: 3
      maxReplicas: 8
      targetCPUUtilizationPercentage: 70

# Production monitoring
monitoring:
  enabled: true
  prometheus:
    enabled: true
    serviceMonitor:
      enabled: true
  grafana:
    enabled: true
    dashboards:
      enabled: true

# Azure storage configuration
storage:
  enabled: true
  type: "azure"
  size: "10Gi"
  azure:
    accountName: "workfxstorage"
    accountKey: "your-account-key"
    containerName: "workfx-ai-prod"
    endpoint: "https://workfxstorage.blob.core.windows.net"

# External database (Azure Database for PostgreSQL)
postgresql:
  enabled: false
  external:
    enabled: true
    host: "your-postgres-server.postgres.database.azure.com"
    port: 5432
    database: "workfx_ai_prod"
    username: "workfx_user@your-postgres-server"
    password: "your-password"
    sslMode: "require"

# External Redis (Azure Cache for Redis)
redis:
  enabled: false
  external:
    enabled: true
    host: "your-redis.redis.cache.windows.net"
    port: 6380
    password: "your-password"
    ssl: true

# Production security
security:
  networkPolicy:
    enabled: true
  rbac:
    enabled: true
    create: true
  secrets:
    enabled: true
    externalSecrets:
      enabled: true
      secretStore:
        name: "azure-key-vault-store"
        kind: "SecretStore"
      refreshInterval: "15m"

# Production backup
backup:
  enabled: true
  schedule: "0 2 * * *"
  retention: "30d"

# Production maintenance
maintenance:
  rollingUpdate:
    maxSurge: 1
    maxUnavailable: 0
  podDisruptionBudget:
    enabled: true
    minAvailable: 2

# Resource quotas
resourceQuota:
  enabled: true
  limits:
    cpu: "8"
    memory: "16Gi"
    persistentvolumeclaims: "20"
