apiVersion: v2
name: workfx-ai
description: WorkFX-AI - Enterprise AI Workflow Platform for Private Cloud Deployment

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities or functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.0.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.0.0"

# Keywords to help users find this chart
keywords:
  - ai
  - workflow
  - enterprise
  - private-cloud
  - automation

# Home page for the chart
home: https://workfx.ai

# Source code repository
sources:
  - https://github.com/your-org/workfx-ai

# Maintainers information
maintainers:
  - name: WorkFX Team
    email: support@workfx.ai
    url: https://workfx.ai

# Icon for the chart
icon: https://workfx.ai/logo.png

# Annotations for the chart
annotations:
  category: AI/ML
  licenses: Proprietary
  vendor: WorkFX

# Dependencies for the chart
dependencies:
  - name: postgresql
    version: 12.5.6
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
    tags:
      - database
      - postgres
  - name: redis
    version: 17.3.2
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
    tags:
      - cache
      - redis
  - name: rabbitmq
    version: 11.8.0
    repository: https://charts.bitnami.com/bitnami
    condition: rabbitmq.enabled
    tags:
      - message-queue
      - rabbitmq
  - name: elasticsearch
    version: 8.5.1
    repository: https://charts.bitnami.com/bitnami
    condition: elasticsearch.enabled
    tags:
      - search
      - elasticsearch
  - name: kibana
    version: 8.5.1
    repository: https://charts.bitnami.com/bitnami
    condition: kibana.enabled
    tags:
      - monitoring
      - kibana
