apiVersion: v2
name: workfx-ai
description: A Helm chart for WorkFX AI Platform - Enterprise AI platform with modular architecture
type: application
version: 0.2.0
appVersion: "1.0.0"
keywords:
  - workfx
  - ai
  - platform
  - enterprise
  - kubernetes
  - helm
home: https://workfx.ai
sources:
  - https://github.com/workfx/workfx-ai
  - https://github.com/workfx/workfx-ai-helm
maintainers:
  - name: WorkFX AI Team
    email: support@workfx.ai
    url: https://workfx.ai
icon: https://workfx.ai/favicon.ico

# Dependencies on sub-charts
dependencies:
  # Database
  - name: postgresql
    version: 12.5.8
    condition: infrastructure.postgresql.enabled
    repository: https://charts.bitnami.com/bitnami
    tags:
      - database
      - postgres
  
  # Cache
  - name: redis
    version: 17.10.3
    condition: infrastructure.redis.enabled
    repository: https://charts.bitnami.com/bitnami
    tags:
      - cache
      - redis
  
  # Message Queue
  - name: kafka
    version: 25.0.0
    condition: infrastructure.kafka.enabled
    repository: https://charts.bitnami.com/bitnami
    tags:
      - messaging
      - kafka
  
  # Search Engine
  - name: elasticsearch
    version: 19.17.0
    condition: infrastructure.elasticsearch.enabled
    repository: https://charts.bitnami.com/bitnami
    tags:
      - search
      - elasticsearch
  
  # Log Management
  - name: kibana
    version: 10.1.0
    condition: infrastructure.kibana.enabled
    repository: https://charts.bitnami.com/bitnami
    tags:
      - logging
      - kibana
  
  # Kafka Management UI
  - name: akhq
    version: 0.23.0
    condition: infrastructure.akhq.enabled
    repository: https://akhq.io/
    tags:
      - monitoring
      - kafka-ui

# Annotations
annotations:
  category: AI/ML
  licenses: Proprietary
  vendor: WorkFX AI
  support: support@workfx.ai
